package traefik

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/lite-dokploy/backend/internal/types"
)

type Manager struct {
	enabled bool
}

func NewManager() *Manager {
	return &Manager{enabled: false}
}

func (m *Manager) Enable() {
	m.enabled = true
}

func (m *Manager) GenerateComposeSnippet(app *types.Application, repoDir string) error {
	if app.Domain == "" || !m.enabled {
		return nil
	}

	snippet := fmt.Sprintf("# Traefik configuration for %s\n"+
		"# Generated by Lite Dokploy\n"+
		"# Uncomment and adapt these labels on your compose service\n"+
		"#\n"+
		"# labels:\n"+
		`#   - "traefik.enable=true"`+"\n"+
		`#   - "traefik.http.routers.%s.rule=Host(`+"`%s`"+`)"`+"\n"+
		`#   - "traefik.http.routers.%s.entrypoints=websecure"`+"\n"+
		`#   - "traefik.http.routers.%s.tls.certresolver=letsencrypt"`+"\n"+
		`#   - "traefik.http.services.%s.loadbalancer.server.port=80"`+"\n"+
		"#\n",
		app.Name, app.Name, app.Domain, app.Name, app.Name, app.Name)

	commentPath := filepath.Join(repoDir, "TRAEFIK_LABELS.md")
	return os.WriteFile(commentPath, []byte(snippet), 0644)
}

func (m *Manager) EnsureTraefikNetwork() error {
	return nil
}
